import jsPDF from 'jspdf'

interface PrescriptionData {
  id: string
  patientName: string
  patientAge?: number
  doctorName: string
  date: string
  medications: Array<{
    name: string
    dosage: string
    frequency: string
    duration: string
    instructions?: string
  }>
  diagnosis?: string
  notes?: string
}

interface CarePlanData {
  patientName: string
  patientAge: string
  diagnosis: string
  problems: Array<{
    number: number
    problem: string
    nursingDiagnosis: string
    goals: {
      shortTerm: string
      longTerm: string
    }
    interventions: string[]
    rationale: string[]
    evaluation: string[]
  }>
  createdAt: string
}

export const generatePrescriptionPDF = (prescription: PrescriptionData) => {
  const doc = new jsPDF()
  
  // Header
  doc.setFontSize(20)
  doc.text('MEDICAL PRESCRIPTION', 105, 20, { align: 'center' })
  
  // Doctor info
  doc.setFontSize(12)
  doc.text(`Dr. ${prescription.doctorName}`, 20, 40)
  doc.text(`Date: ${prescription.date}`, 20, 50)
  
  // Patient info
  doc.text(`Patient: ${prescription.patientName}`, 20, 70)
  if (prescription.patientAge) {
    doc.text(`Age: ${prescription.patientAge}`, 20, 80)
  }
  
  // Diagnosis
  if (prescription.diagnosis) {
    doc.text(`Diagnosis: ${prescription.diagnosis}`, 20, 100)
  }
  
  // Medications
  doc.setFontSize(14)
  doc.text('MEDICATIONS:', 20, 120)
  
  let yPos = 135
  prescription.medications.forEach((med, index) => {
    doc.setFontSize(12)
    doc.text(`${index + 1}. ${med.name}`, 25, yPos)
    doc.text(`   Dosage: ${med.dosage}`, 25, yPos + 10)
    doc.text(`   Frequency: ${med.frequency}`, 25, yPos + 20)
    doc.text(`   Duration: ${med.duration}`, 25, yPos + 30)
    if (med.instructions) {
      doc.text(`   Instructions: ${med.instructions}`, 25, yPos + 40)
      yPos += 55
    } else {
      yPos += 45
    }
  })
  
  // Notes
  if (prescription.notes) {
    doc.text('Notes:', 20, yPos + 10)
    doc.text(prescription.notes, 20, yPos + 20)
  }
  
  // Footer
  doc.setFontSize(10)
  doc.text('Generated by MedPro - Digital Health Assistant', 105, 280, { align: 'center' })
  
  return doc
}

export const downloadPrescriptionPDF = (prescription: PrescriptionData) => {
  const doc = generatePrescriptionPDF(prescription)
  doc.save(`prescription-${prescription.patientName}-${prescription.date}.pdf`)
}

export const emailPrescriptionPDF = async (prescription: PrescriptionData, email: string) => {
  const doc = generatePrescriptionPDF(prescription)
  const pdfBlob = doc.output('blob')
  
  // Convert to base64 for email
  const reader = new FileReader()
  return new Promise((resolve, reject) => {
    reader.onload = () => {
      const base64 = reader.result?.toString().split(',')[1]
      resolve(base64)
    }
    reader.onerror = reject
    reader.readAsDataURL(pdfBlob)
  })
}

export const generateCarePlanPDF = (carePlan: CarePlanData) => {
  const doc = new jsPDF()
  
  // Header
  doc.setFontSize(20)
  doc.text('NURSING CARE PLAN', 105, 20, { align: 'center' })
  
  // Patient info
  doc.setFontSize(12)
  doc.text(`Patient: ${carePlan.patientName}`, 20, 40)
  doc.text(`Age: ${carePlan.patientAge}`, 20, 50)
  doc.text(`Diagnosis: ${carePlan.diagnosis}`, 20, 60)
  doc.text(`Date: ${new Date(carePlan.createdAt).toLocaleDateString()}`, 20, 70)
  
  let yPos = 90
  
  // Problems
  carePlan.problems.forEach((problem, index) => {
    if (yPos > 250) {
      doc.addPage()
      yPos = 20
    }
    
    doc.setFontSize(14)
    doc.text(`Problem ${problem.number}: ${problem.problem}`, 20, yPos)
    yPos += 10
    
    doc.setFontSize(10)
    doc.text(`Nursing Diagnosis: ${problem.nursingDiagnosis}`, 20, yPos)
    yPos += 15
    
    doc.text(`Short-term Goal: ${problem.goals.shortTerm}`, 20, yPos)
    yPos += 10
    doc.text(`Long-term Goal: ${problem.goals.longTerm}`, 20, yPos)
    yPos += 15
    
    doc.text('Interventions:', 20, yPos)
    yPos += 8
    problem.interventions.forEach((intervention) => {
      doc.text(`• ${intervention}`, 25, yPos)
      yPos += 8
    })
    
    yPos += 10
  })
  
  // Footer
  doc.setFontSize(8)
  doc.text('Generated by MedPro - Digital Health Assistant', 105, 285, { align: 'center' })
  
  doc.save(`care-plan-${carePlan.patientName}-${new Date().toISOString().split('T')[0]}.pdf`)
}